// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmxctdemerbiczzdatsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNteGN0ZGVtZXJiaWN6emRhdHNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODA1MjAsImV4cCI6MjA1ODY1NjUyMH0.VEwj2iucFCfgsH9oUxytjJNGECJU9jXOCOG1KAcWZ_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);